import "server-only";
import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import {
  SNAPSHOT_LIMITS,
  SNAPSHOT_TIMEOUT_MS,
  TOURNAMENT,
  VENUE_CONTEXT,
} from "@/lib/constants";
import { getServerEnv } from "@/lib/env";
import { logError, logWarning } from "@/lib/logger";
import { clamp, entityId, type StadiumSnapshot } from "@/lib/stadium-data";
import { synthesizeSnapshot } from "@/lib/synthetic-snapshot";

/**
 * Server-only source of the live operations snapshot.
 *
 * The snapshot is generated by Gemini as structured JSON so the dashboard
 * contains no hardcoded operational data. If the model is disabled (mock mode),
 * unconfigured, or errors, a computed procedural snapshot is used so the page
 * always renders.
 */

const aiSnapshotSchema = z.object({
  venue: z.string().min(1).max(SNAPSHOT_LIMITS.venueLength),
  zones: z
    .array(
      z.object({
        name: z.string().min(1).max(SNAPSHOT_LIMITS.nameLength),
        capacity: z.number().int().positive().max(SNAPSHOT_LIMITS.capacity),
        occupancy: z.number().int().nonnegative().max(SNAPSHOT_LIMITS.capacity),
      }),
    )
    .min(1)
    .max(SNAPSHOT_LIMITS.maxZones),
  gates: z
    .array(
      z.object({
        name: z.string().min(1).max(SNAPSHOT_LIMITS.nameLength),
        isOpen: z.boolean(),
        throughputPerMin: z
          .number()
          .int()
          .nonnegative()
          .max(SNAPSHOT_LIMITS.throughputPerMin),
        waitMinutes: z
          .number()
          .int()
          .nonnegative()
          .max(SNAPSHOT_LIMITS.waitMinutes),
      }),
    )
    .min(1)
    .max(SNAPSHOT_LIMITS.maxGates),
  incidents: z
    .array(
      z.object({
        severity: z.enum(["low", "medium", "high"]),
        message: z.string().min(1).max(SNAPSHOT_LIMITS.messageLength),
        minutesAgo: z
          .number()
          .int()
          .nonnegative()
          .max(SNAPSHOT_LIMITS.incidentAgeMinutes),
        zoneName: z.string().min(1).max(SNAPSHOT_LIMITS.nameLength),
      }),
    )
    .max(SNAPSHOT_LIMITS.maxIncidents),
});

type AiSnapshot = z.infer<typeof aiSnapshotSchema>;

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/** Normalizes validated AI output into a domain snapshot with stable ids. */
function normalizeSnapshot(
  ai: AiSnapshot,
  generatedAt: number,
): StadiumSnapshot {
  // Incidents reference zones by display name; resolve them to the generated
  // zone ids so references stay internally consistent. Names the model made
  // up without a matching zone degrade to a slug rather than a broken id.
  const zoneIdByName = new Map(
    ai.zones.map((zone, index) => [zone.name, entityId("zone", index)]),
  );

  return {
    venue: ai.venue,
    generatedAt,
    zones: ai.zones.map((zone, index) => ({
      id: entityId("zone", index),
      name: zone.name,
      capacity: zone.capacity,
      occupancy: clamp(zone.occupancy, 0, zone.capacity),
    })),
    gates: ai.gates.map((gate, index) => ({
      id: entityId("gate", index),
      name: gate.name,
      isOpen: gate.isOpen,
      throughputPerMin: gate.throughputPerMin,
      waitMinutes: gate.waitMinutes,
    })),
    incidents: ai.incidents.map((incident, index) => ({
      id: entityId("incident", index),
      zoneId: zoneIdByName.get(incident.zoneName) ?? slug(incident.zoneName),
      severity: incident.severity,
      message: incident.message,
      minutesAgo: incident.minutesAgo,
    })),
  };
}

/** Prompt instructing Gemini to emit a realistic operations snapshot as JSON. */
export function buildSnapshotPrompt(): string {
  return [
    `Generate a realistic, plausible real-time operations snapshot for ${VENUE_CONTEXT} during a ${TOURNAMENT} match in progress.`,
    "Return ONLY JSON (no markdown, no commentary) with this exact shape:",
    '{ "venue": string, "zones": [{ "name": string, "capacity": integer, "occupancy": integer }],',
    '"gates": [{ "name": string, "isOpen": boolean, "throughputPerMin": integer, "waitMinutes": integer }],',
    '"incidents": [{ "severity": "low"|"medium"|"high", "message": string, "minutesAgo": integer, "zoneName": string }] }',
    "Provide 4-6 zones, 5-8 gates, and 0-4 incidents. Occupancy must not exceed capacity.",
    "Vary the figures so the operation looks live and busy but coherent. Do not include personal data.",
  ].join(" ");
}

/**
 * Combines an optional caller signal with a timeout budget. Equivalent to
 * `AbortSignal.any`, which is not yet available in every runtime this code is
 * tested under.
 */
export function withTimeoutSignal(
  signal: AbortSignal | undefined,
  timeoutMs: number,
): AbortSignal {
  const timeout = AbortSignal.timeout(timeoutMs);
  if (!signal) {
    return timeout;
  }
  if (signal.aborted) {
    return signal;
  }
  const controller = new AbortController();
  const propagate = (source: AbortSignal) => () =>
    controller.abort(source.reason);
  signal.addEventListener("abort", propagate(signal), { once: true });
  timeout.addEventListener("abort", propagate(timeout), { once: true });
  return controller.signal;
}

/**
 * Returns the current operations snapshot, generated by Gemini when available
 * and falling back to a computed procedural snapshot otherwise.
 */
export async function generateOperationsSnapshot(
  signal?: AbortSignal,
): Promise<StadiumSnapshot> {
  const env = getServerEnv();
  const generatedAt = Date.now();

  if (env.STADIUM_AI_MOCK || !env.GEMINI_API_KEY) {
    return synthesizeSnapshot(generatedAt);
  }

  // Bound the upstream call so a slow provider can never stall page rendering;
  // a timeout degrades to the procedural fallback like any other failure.
  const abortSignal = withTimeoutSignal(signal, SNAPSHOT_TIMEOUT_MS);

  try {
    const client = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });
    const response = await client.models.generateContent({
      model: env.GEMINI_MODEL,
      contents: buildSnapshotPrompt(),
      config: {
        responseMimeType: "application/json",
        temperature: 1,
        abortSignal,
      },
    });
    const parsed = aiSnapshotSchema.parse(JSON.parse(response.text ?? ""));
    return normalizeSnapshot(parsed, generatedAt);
  } catch (error) {
    // A timeout or caller cancellation is expected degradation, not a fault;
    // log it as a warning so genuine provider errors stay distinguishable.
    if (abortSignal.aborted) {
      logWarning("ops-snapshot", "snapshot generation aborted");
    } else {
      logError("ops-snapshot", error);
    }
    return synthesizeSnapshot(generatedAt);
  }
}
