import "server-only";
import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import { TOURNAMENT, VENUE_CONTEXT } from "@/lib/constants";
import { getServerEnv } from "@/lib/env";
import { logError } from "@/lib/logger";
import {
  clamp,
  synthesizeSnapshot,
  type StadiumSnapshot,
} from "@/lib/stadium-data";

/**
 * Server-only source of the live operations snapshot.
 *
 * The snapshot is generated by Gemini as structured JSON so the dashboard
 * contains no hardcoded operational data. If the model is disabled (mock mode),
 * unconfigured, or errors, a computed procedural snapshot is used so the page
 * always renders.
 */

const aiSnapshotSchema = z.object({
  venue: z.string().min(1).max(120),
  zones: z
    .array(
      z.object({
        name: z.string().min(1).max(60),
        capacity: z.number().int().positive().max(200000),
        occupancy: z.number().int().nonnegative().max(200000),
      }),
    )
    .min(1)
    .max(12),
  gates: z
    .array(
      z.object({
        name: z.string().min(1).max(60),
        isOpen: z.boolean(),
        throughputPerMin: z.number().int().nonnegative().max(2000),
        waitMinutes: z.number().int().nonnegative().max(240),
      }),
    )
    .min(1)
    .max(20),
  incidents: z
    .array(
      z.object({
        severity: z.enum(["low", "medium", "high"]),
        message: z.string().min(1).max(240),
        minutesAgo: z.number().int().nonnegative().max(600),
        zoneName: z.string().min(1).max(60),
      }),
    )
    .max(20),
});

type AiSnapshot = z.infer<typeof aiSnapshotSchema>;

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/** Normalizes validated AI output into a domain snapshot with stable ids. */
function normalizeSnapshot(
  ai: AiSnapshot,
  generatedAt: number,
): StadiumSnapshot {
  return {
    venue: ai.venue,
    generatedAt,
    zones: ai.zones.map((zone, index) => ({
      id: `zone-${index + 1}`,
      name: zone.name,
      capacity: zone.capacity,
      occupancy: clamp(zone.occupancy, 0, zone.capacity),
    })),
    gates: ai.gates.map((gate, index) => ({
      id: `gate-${index + 1}`,
      name: gate.name,
      isOpen: gate.isOpen,
      throughputPerMin: gate.throughputPerMin,
      waitMinutes: gate.waitMinutes,
    })),
    incidents: ai.incidents.map((incident, index) => ({
      id: `incident-${index + 1}`,
      zoneId: slug(incident.zoneName),
      severity: incident.severity,
      message: incident.message,
      minutesAgo: incident.minutesAgo,
    })),
  };
}

/** Prompt instructing Gemini to emit a realistic operations snapshot as JSON. */
export function buildSnapshotPrompt(): string {
  return [
    `Generate a realistic, plausible real-time operations snapshot for ${VENUE_CONTEXT} during a ${TOURNAMENT} match in progress.`,
    "Return ONLY JSON (no markdown, no commentary) with this exact shape:",
    '{ "venue": string, "zones": [{ "name": string, "capacity": integer, "occupancy": integer }],',
    '"gates": [{ "name": string, "isOpen": boolean, "throughputPerMin": integer, "waitMinutes": integer }],',
    '"incidents": [{ "severity": "low"|"medium"|"high", "message": string, "minutesAgo": integer, "zoneName": string }] }',
    "Provide 4-6 zones, 5-8 gates, and 0-4 incidents. Occupancy must not exceed capacity.",
    "Vary the figures so the operation looks live and busy but coherent. Do not include personal data.",
  ].join(" ");
}

/**
 * Returns the current operations snapshot, generated by Gemini when available
 * and falling back to a computed procedural snapshot otherwise.
 */
export async function generateOperationsSnapshot(
  signal?: AbortSignal,
): Promise<StadiumSnapshot> {
  const env = getServerEnv();
  const generatedAt = Date.now();

  if (env.STADIUM_AI_MOCK || !env.GEMINI_API_KEY) {
    return synthesizeSnapshot(generatedAt);
  }

  try {
    const client = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });
    const response = await client.models.generateContent({
      model: env.GEMINI_MODEL,
      contents: buildSnapshotPrompt(),
      config: {
        responseMimeType: "application/json",
        temperature: 1,
        abortSignal: signal,
      },
    });
    const parsed = aiSnapshotSchema.parse(JSON.parse(response.text ?? ""));
    return normalizeSnapshot(parsed, generatedAt);
  } catch (error) {
    logError("ops-snapshot", error);
    return synthesizeSnapshot(generatedAt);
  }
}
