import {
  CRITICAL_INCIDENT_COUNT,
  CRITICAL_OCCUPANCY_PCT,
  ELEVATED_INCIDENT_COUNT,
  ELEVATED_OCCUPANCY_PCT,
  HIGH_SEVERITY_SCORE,
  MEDIUM_SEVERITY_SCORE,
} from "@/lib/constants";

/**
 * Stadium operations domain model and pure derivation helpers.
 *
 * There is no hardcoded operational dataset in this project. In production the
 * live snapshot is generated by Gemini (see `lib/ops-source.ts`); offline and
 * in tests it is generated procedurally (see `lib/synthetic-snapshot.ts`).
 * This module owns only the domain types and the pure functions that read a
 * snapshot — it has no data of its own.
 */

/** A seating zone and its live occupancy. */
export interface Zone {
  readonly id: string;
  readonly name: string;
  readonly capacity: number;
  readonly occupancy: number;
}

/** An entry gate and its live throughput. */
export interface Gate {
  readonly id: string;
  readonly name: string;
  readonly isOpen: boolean;
  readonly throughputPerMin: number;
  readonly waitMinutes: number;
}

/** Severity of an operational incident. */
export type IncidentSeverity = "low" | "medium" | "high";

/** A single operational incident. */
export interface Incident {
  readonly id: string;
  readonly zoneId: string;
  readonly severity: IncidentSeverity;
  readonly message: string;
  readonly minutesAgo: number;
}

/** A full point-in-time view of stadium operations. */
export interface StadiumSnapshot {
  readonly venue: string;
  readonly generatedAt: number;
  readonly zones: readonly Zone[];
  readonly gates: readonly Gate[];
  readonly incidents: readonly Incident[];
}

/** Overall operational posture derived from a snapshot. */
export type OperationalStatus = "normal" | "elevated" | "critical";

/** Aggregate metrics derived from a {@link StadiumSnapshot}. */
export interface StadiumMetrics {
  readonly totalCapacity: number;
  readonly totalOccupancy: number;
  readonly occupancyPct: number;
  readonly openGates: number;
  readonly activeIncidents: number;
  readonly busiestZone: Zone;
  readonly longestWaitGate: Gate;
  readonly status: OperationalStatus;
}

/** Builds a stable, 1-based sequential id such as `zone-1`. */
export function entityId(prefix: string, index: number): string {
  return `${prefix}-${index + 1}`;
}

/** Clamps `value` to the inclusive `[min, max]` range. */
export function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

/** Returns the element of `items` with the highest `score`. */
export function maxBy<T>(items: readonly T[], score: (item: T) => number): T {
  return items.reduce((best, item) =>
    score(item) > score(best) ? item : best,
  );
}

/** Occupancy of a zone as a whole-number percentage; 0 for zero-capacity zones. */
export function zoneOccupancyPct(zone: Zone): number {
  if (zone.capacity <= 0) {
    return 0;
  }
  return Math.round((zone.occupancy / zone.capacity) * 100);
}

/** Maps a 0–1 score to an incident severity band. */
export function severityFromScore(score: number): IncidentSeverity {
  if (score >= HIGH_SEVERITY_SCORE) {
    return "high";
  }
  if (score >= MEDIUM_SEVERITY_SCORE) {
    return "medium";
  }
  return "low";
}

/**
 * Classifies overall operational posture from occupancy and incident load.
 * Critical conditions escalate ahead of merely elevated ones.
 */
export function classifyStatus(
  occupancyPct: number,
  activeIncidents: number,
): OperationalStatus {
  if (
    occupancyPct >= CRITICAL_OCCUPANCY_PCT ||
    activeIncidents >= CRITICAL_INCIDENT_COUNT
  ) {
    return "critical";
  }
  if (
    occupancyPct >= ELEVATED_OCCUPANCY_PCT ||
    activeIncidents >= ELEVATED_INCIDENT_COUNT
  ) {
    return "elevated";
  }
  return "normal";
}

/** Derives aggregate metrics from a snapshot. */
export function deriveMetrics(snapshot: StadiumSnapshot): StadiumMetrics {
  const totalCapacity = snapshot.zones.reduce(
    (sum, zone) => sum + zone.capacity,
    0,
  );
  const totalOccupancy = snapshot.zones.reduce(
    (sum, zone) => sum + zone.occupancy,
    0,
  );
  const occupancyPct =
    totalCapacity > 0 ? Math.round((totalOccupancy / totalCapacity) * 100) : 0;
  const openGates = snapshot.gates.filter((gate) => gate.isOpen).length;
  const activeIncidents = snapshot.incidents.length;

  return {
    totalCapacity,
    totalOccupancy,
    occupancyPct,
    openGates,
    activeIncidents,
    busiestZone: maxBy(snapshot.zones, zoneOccupancyPct),
    longestWaitGate: maxBy(snapshot.gates, (gate) => gate.waitMinutes),
    status: classifyStatus(occupancyPct, activeIncidents),
  };
}

/**
 * Renders a compact, model-friendly summary of live operations for grounding
 * the AI briefing. Free of PII.
 */
export function summarizeForPrompt(
  snapshot: StadiumSnapshot,
  metrics: StadiumMetrics,
): string {
  const zoneLines = snapshot.zones
    .map((zone) => `- ${zone.name}: ${zoneOccupancyPct(zone)}% full`)
    .join("\n");
  const gateLines = snapshot.gates
    .map(
      (gate) =>
        `- ${gate.name}: ${gate.waitMinutes} min wait, ${gate.throughputPerMin}/min throughput`,
    )
    .join("\n");
  const incidentLines =
    snapshot.incidents.length === 0
      ? "- None active."
      : snapshot.incidents
          .map(
            (incident) =>
              `- [${incident.severity}] ${incident.message} (${incident.minutesAgo} min ago)`,
          )
          .join("\n");

  return [
    `Venue: ${snapshot.venue}`,
    `Overall occupancy: ${metrics.occupancyPct}% (${metrics.totalOccupancy} of ${metrics.totalCapacity}).`,
    `Operational status: ${metrics.status}.`,
    `Busiest zone: ${metrics.busiestZone.name}.`,
    `Longest gate wait: ${metrics.longestWaitGate.name} at ${metrics.longestWaitGate.waitMinutes} min.`,
    "",
    "Zones:",
    zoneLines,
    "",
    "Gates:",
    gateLines,
    "",
    "Active incidents:",
    incidentLines,
  ].join("\n");
}
