import { VENUE_CONTEXT } from "@/lib/constants";

/**
 * Stadium operations domain model, derivation helpers, and a procedural
 * generator.
 *
 * There is no hardcoded operational dataset in this project. In production the
 * live snapshot is generated by Gemini (see `lib/ops-source.ts`); this module
 * provides the pure metric-derivation helpers plus a computed procedural
 * generator used as a deterministic offline/test fallback.
 */

/** A seating zone and its live occupancy. */
export interface Zone {
  readonly id: string;
  readonly name: string;
  readonly capacity: number;
  readonly occupancy: number;
}

/** An entry gate and its live throughput. */
export interface Gate {
  readonly id: string;
  readonly name: string;
  readonly isOpen: boolean;
  readonly throughputPerMin: number;
  readonly waitMinutes: number;
}

/** Severity of an operational incident. */
export type IncidentSeverity = "low" | "medium" | "high";

/** A single operational incident. */
export interface Incident {
  readonly id: string;
  readonly zoneId: string;
  readonly severity: IncidentSeverity;
  readonly message: string;
  readonly minutesAgo: number;
}

/** A full point-in-time view of stadium operations. */
export interface StadiumSnapshot {
  readonly venue: string;
  readonly generatedAt: number;
  readonly zones: readonly Zone[];
  readonly gates: readonly Gate[];
  readonly incidents: readonly Incident[];
}

/** Overall operational posture derived from a snapshot. */
export type OperationalStatus = "normal" | "elevated" | "critical";

/** Aggregate metrics derived from a {@link StadiumSnapshot}. */
export interface StadiumMetrics {
  readonly totalCapacity: number;
  readonly totalOccupancy: number;
  readonly occupancyPct: number;
  readonly openGates: number;
  readonly activeIncidents: number;
  readonly busiestZone: Zone;
  readonly longestWaitGate: Gate;
  readonly status: OperationalStatus;
}

/** Deterministic pseudo-random generator (mulberry32). */
function createRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Clamps `value` to the inclusive `[min, max]` range. */
export function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

/** Returns the element of `items` with the highest `score`. */
export function maxBy<T>(items: readonly T[], score: (item: T) => number): T {
  return items.reduce((best, item) =>
    score(item) > score(best) ? item : best,
  );
}

/** Occupancy of a zone as a whole-number percentage. */
export function zoneOccupancyPct(zone: Zone): number {
  return Math.round((zone.occupancy / zone.capacity) * 100);
}

/** Maps a 0–1 score to an incident severity band. */
export function severityFromScore(score: number): IncidentSeverity {
  if (score >= 0.85) {
    return "high";
  }
  if (score >= 0.6) {
    return "medium";
  }
  return "low";
}

/**
 * Classifies overall operational posture from occupancy and incident load.
 * Critical conditions escalate ahead of merely elevated ones.
 */
export function classifyStatus(
  occupancyPct: number,
  activeIncidents: number,
): OperationalStatus {
  if (occupancyPct >= 90 || activeIncidents >= 3) {
    return "critical";
  }
  if (occupancyPct >= 78 || activeIncidents >= 1) {
    return "elevated";
  }
  return "normal";
}

/**
 * Generates a snapshot procedurally from a numeric seed.
 *
 * All values are computed at call time — there is no stored dataset. Used as a
 * deterministic fallback when the AI generator is unavailable (offline, tests,
 * or a transient provider error).
 */
export function synthesizeSnapshot(seed: number): StadiumSnapshot {
  const random = createRandom(seed);

  const zones: Zone[] = Array.from({ length: 5 }, (_, index) => {
    const capacity = 12000 + Math.round(random() * 12000);
    const fill = clamp(0.55 + (random() - 0.4) * 0.45, 0, 1);
    return {
      id: `zone-${index + 1}`,
      name: `Seating Zone ${index + 1}`,
      capacity,
      occupancy: Math.round(capacity * fill),
    };
  });

  const gates: Gate[] = Array.from({ length: 6 }, (_, index) => ({
    id: `gate-${index + 1}`,
    name: `Gate ${index + 1}`,
    isOpen: true,
    throughputPerMin: 60 + Math.round(random() * 90),
    waitMinutes: Math.round(random() * 14),
  }));

  const incidentCount = Math.floor(random() * 4);
  const incidents: Incident[] = Array.from(
    { length: incidentCount },
    (_, index) => {
      const zoneNumber = 1 + Math.floor(random() * zones.length);
      const severity = severityFromScore(random());
      return {
        id: `incident-${index + 1}`,
        zoneId: `zone-${zoneNumber}`,
        severity,
        message: `Reported ${severity}-severity activity in Seating Zone ${zoneNumber}.`,
        minutesAgo: 1 + Math.floor(random() * 30),
      };
    },
  );

  return { venue: VENUE_CONTEXT, generatedAt: seed, zones, gates, incidents };
}

/** Derives aggregate metrics from a snapshot. */
export function deriveMetrics(snapshot: StadiumSnapshot): StadiumMetrics {
  const totalCapacity = snapshot.zones.reduce(
    (sum, zone) => sum + zone.capacity,
    0,
  );
  const totalOccupancy = snapshot.zones.reduce(
    (sum, zone) => sum + zone.occupancy,
    0,
  );
  const occupancyPct = Math.round((totalOccupancy / totalCapacity) * 100);
  const openGates = snapshot.gates.filter((gate) => gate.isOpen).length;
  const activeIncidents = snapshot.incidents.length;

  return {
    totalCapacity,
    totalOccupancy,
    occupancyPct,
    openGates,
    activeIncidents,
    busiestZone: maxBy(snapshot.zones, zoneOccupancyPct),
    longestWaitGate: maxBy(snapshot.gates, (gate) => gate.waitMinutes),
    status: classifyStatus(occupancyPct, activeIncidents),
  };
}

/**
 * Renders a compact, model-friendly summary of live operations for grounding
 * the AI briefing. Free of PII.
 */
export function summarizeForPrompt(
  snapshot: StadiumSnapshot,
  metrics: StadiumMetrics,
): string {
  const zoneLines = snapshot.zones
    .map((zone) => `- ${zone.name}: ${zoneOccupancyPct(zone)}% full`)
    .join("\n");
  const gateLines = snapshot.gates
    .map(
      (gate) =>
        `- ${gate.name}: ${gate.waitMinutes} min wait, ${gate.throughputPerMin}/min throughput`,
    )
    .join("\n");
  const incidentLines =
    snapshot.incidents.length === 0
      ? "- None active."
      : snapshot.incidents
          .map(
            (incident) =>
              `- [${incident.severity}] ${incident.message} (${incident.minutesAgo} min ago)`,
          )
          .join("\n");

  return [
    `Venue: ${snapshot.venue}`,
    `Overall occupancy: ${metrics.occupancyPct}% (${metrics.totalOccupancy} of ${metrics.totalCapacity}).`,
    `Operational status: ${metrics.status}.`,
    `Busiest zone: ${metrics.busiestZone.name}.`,
    `Longest gate wait: ${metrics.longestWaitGate.name} at ${metrics.longestWaitGate.waitMinutes} min.`,
    "",
    "Zones:",
    zoneLines,
    "",
    "Gates:",
    gateLines,
    "",
    "Active incidents:",
    incidentLines,
  ].join("\n");
}
